home:
  pattern:  /
  defaults: { _controller: AppBundle:Default:index }

contact:
  pattern: /contact
  defaults:
    _controller: FrameworkBundle:Template:template
    template: 'AppBundle:Default:contact.html.twig'

book_list:
  pattern: /books/list/{page}/{key}
  defaults:
    _controller: AppBundle:Book:list
    page: 1
    key: null

goto_page:
  pattern: /books/gotopage
  defaults: {_controller: AppBundle:Book:gotopage}
  requirements:
    _method: POST

books_search:
  pattern: /books/search
  defaults: {_controller: AppBundle:Book:search}
  requirements:
    _method: POST

book_detail:
  pattern: /books/{id}.html
  defaults: { _controller: AppBundle:Book:detail}

tag_list:
  pattern: /books/tag/{page}/{tag}
  defaults: {_controller: AppBundle:Book:taglist, page:1}

tags_add:
  pattern: /books/addtag
  defaults: {_controller: AppBundle:Book:tagsAdd}
  requirements:
    _method: POST

cover:
  pattern: /books/cover/{id}_{title}_{author}_{width}.png
  defaults: {_controller: AppBundle:Default:cover, width: 300}

reading_list:
  pattern: /books/readings/{page}
  defaults: {_controller: AppBundle:Reading:list, page:1}

member_search:
  pattern: /member/search/{page}
  defaults: {_controller: AppBundle:Search:search, page:1}

member_add:
  pattern: /member/add
  defaults: {_controller: AppBundle:Member:add}

member_delete:
  pattern: /member/delete/
  defaults: {_controller: AppBundle:Member:delete}

member_profile:
  pattern: /member/{username}
  defaults: {_controller: AppBundle:Member:profile}

member:
  pattern: /member
  defaults: {_controller: AppBundle:Member:manage}

testRequest:
  pattern: /test/request/{foo}
  defaults:
    foo: default_foo
    _controller: AppBundle:Test:request

testRespose:
  pattern: /test/response
  defaults: {_controller: AppBundle:Test:response}

test:
  pattern: /test/{foo}
  defaults:
    foo: 1
    _controller: AppBundle:Test:index

