AppBundle\Entity\BookReview:
    type: entity
    repositoryClass: AppBundle\Entity\ReadRepository
    table: book_review
    indexes:
        book_review_ibfk_1:
            columns:
                - headlineid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        datein:
            type: date
            nullable: false
            comment: ''
        uri:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: URI
    manyToOne:
        headlineid:
            targetEntity: BookHeadline
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                headlineid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
