AppBundle\Entity\BookTaglist:
    type: entity
    repositoryClass: AppBundle\Entity\BookRepository
    table: book_taglist
    indexes:
        bookid_2:
            columns:
                - bookid
    uniqueConstraints:
        bookid:
            columns:
                - bookid
                - tag
    id:
        tid:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tag:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    manyToOne:
        bookid:
            targetEntity: BookBook
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                bookid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
