AppBundle\Entity\Members:
    type: entity
    repositoryClass: AppBundle\Entity\MembersRepository
    table: members
    uniqueConstraints:
        UniqueUsername:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 32
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        country:
            type: string
            nullable: false
            length: 16
            fixed: false
            comment: ''
        province:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
        city:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        postalCode:
            type: string
            nullable: false
            length: 7
            fixed: false
            comment: ''
            column: postal_code
        dateOfBirth:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: ''
            column: date_of_birth
        category:
            type: string
            nullable: false
            length: 32
            fixed: false
            comment: ''
        height:
            type: string
            nullable: false
            length: 5
            fixed: false
            comment: ''
        weight:
            type: string
            nullable: false
            length: 7
            fixed: false
            comment: ''
        bodyType:
            type: string
            nullable: false
            length: 16
            fixed: false
            comment: ''
            column: body_type
        ethnicity:
            type: string
            nullable: false
            length: 26
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
