AppBundle\Entity\Qotd:
    type: entity
    repositoryClass: AppBundle\Entity\QotdRepository
    table: qotd
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        quote:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        source:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
