<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookHeadlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookHeadlineRepository extends EntityRepository
{
    public function getResultAndCount($page, $readings_per_page)
    {
        // Get the book count
        $em = $this->getEntityManager();
        $q1 = $em->createQuery('select count(bh.id) bhc from AppBundle:BookHeadline bh');

        $res1 = $q1->getSingleResult();
        $count = $res1['bhc'];

        // Now get the wanted result specified by page
        $repo = $em->getRepository('AppBundle:BookHeadline');
        $q2 = $repo->createQueryBuilder('r')
                ->setMaxResults($readings_per_page)
                ->setFirstResult(($page - 1) * $readings_per_page)
                ->orderBy('r.id', 'desc');

        $q2 = $q2->getQuery();

        $res2 = $q2->getResult();

        return array($res2, $count);
    }
}
